=== IDE Config and Code Style

HARUK tiene un estilo de formato del codigo que se hace cumplir a través del proceso de compilación en maven.

La aplicación del estilo se realiza usando el plugin de `Eclipse code formatter`, usando los archivos en la carpeta `ide-config`.

El codigo será formateado por defecto cuando ejecuta `mvn compile`.

El pipeline de Jenkins validará el cumplimiento del formato y fallará si no se cumple, por esta razón es recomendado ejecutar `mvn clean compile` siempre antes de hacer push al repositorio.

Si quiere ejecutar el formateo sin realizar una compilación completa, puede ejecutar `mvn process-sources`.

=== Configuración de IntelliJ IDEA

Abra la ventana de _**Preferencias**_ o (_**Ajustes**_ dependiendo de la versión).
Navegue a _Plugins_ e installe el [Eclipse Code Formatter Plugin](https://plugins.jetbrains.com/plugin/6546-eclipse-code-formatter) del Marketplace.

Reinicie su IDE, abra la ventana de _**Preferencias**_ o (_**Ajustes**_) de nuevo y navegue a _**Otros ajustes**_ -> _**Eclipse code formatter**_.
Seleccione _**Use the Eclipse Code Formatter**_, cambie la opción _Eclipse Java Formatter Config File_ para apuntar al archivo _**code-style.xml**_ del directorio _**ide-config**_.
Asegurese de activar la opción __**Optimize Imports**__ y asigne el archivo `eclipse.importorder` como archivo de configuración.