SELECT TAS.NAME AS task, COUNT(*) as count
FROM SALES_ACTIVITIES a
         INNER JOIN SALES_ACTIVITIES_PURPOSES p ON p.ID = a.PURPOSE_ID
         INNER JOIN BS_CUSTOMERS_BUSINESS_VIEW bs ON bs.CUSTOMER_ID = a.BUYER_ID
         INNER JOIN SALES_ACTIVITIES_TASKS_DETAILS TAD ON TAD.ACTIVITY_ID = A.ID
         INNER JOIN SALES_ACTIVITIES_TASKS TAS ON TAS.ID = TAD.TASK_ID
WHERE a.TENANT_ID = '{{tenant_id}}'
  AND ('{{salesRepId}}' IS NULL OR A.SALES_REP_ID = '{{salesRepId}}')
  AND ('{{businessId}}' IS NULL OR BS.BUSINESS_ID = '{{businessId}}')
  AND A.ACTIVITY_DATE BETWEEN '{{startDate}}' AND '{{endDate}}'
GROUP BY task
